apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simpledevice-api
  namespace: simpledevice-prod
spec:
  ingressClassName: nginx
  rules:
  - host: simpledevice-api.savoliuk.pp.ua
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simpledevice-api
            port:
              number: 80
