apiVersion: v1
kind: Service
metadata:
  name: simpledevice-api
  labels:
    app: simpledevice-api
spec:
  type: ClusterIP
  selector:
    app: simpledevice-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
