apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simpledevice-dev

resources:
  - ../../base
  - postgres.yaml

images:
  - name: simpledevice-api
    newName: ghcr.io/savoliukk/simpledevice-api
    newTag: latest

configMapGenerator:
  - name: simpledevice-api-config
    behavior: merge
    literals:
      - ASPNETCORE_ENVIRONMENT=Development
