apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simpledevice-dev

resources:
  - ../../base
  - ingress.yaml
  - externalsecret.yaml

# Non-secret configuration (safe to keep in Git)
configMapGenerator:
  - name: simpledevice-api-config
    literals:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development

# Keep stable names (no hash suffix) so references stay constant
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: simpledevice-api
    newName: ghcr.io/savoliukk/simpledevice-api
    newTag: latest
